### PR TITLE
corrected stacking problem

### LINKED ISSUE #64: Word features popover has incorrect z-index
Image

### PR DESCRIPTION
**Pull request by longrunningprocess**
resolves #64 

image

### CODE REVIEW

File: src/lib/examples/semantic_encoding/Features.svelte
Comment (longrunningprocess) [inline src/lib/examples/semantic_encoding/Features.svelte:1]: @craigp-atw I could not figure out the intent of this, maybe you can reassure me this is ok to remove.

Comment (craigp-atw) [reply src/lib/examples/semantic_encoding/Features.svelte:1]: I don't know exactly, likely just to get it above the stuff in the parent div. Looks like your change makes it moot. Don't know how reassuring that is haha

File: src/lib/examples/Examples.svelte [hunk 1]
```diff
@@ -82,3 +82,10 @@
 		{/if}
 	{/await}
 </article>
+
+<style>
+	/* this corrects a problem where the features popup was getting hidden behind the next details element below it */
+	details[open] {
```
Comment (craigp-atw) [inline src/lib/examples/Examples.svelte:88]: slick!

**Review by craigp-atw — APPROVED** [review]
